In [3]:
!pip install numpy

In [4]:
import numpy as np

marks = np.array([88, 90, 30, 45, 75])

mark_add = marks + 5

print(mark_add)


[93 95 35 50 80]


In [ ]:
import numpy as np

marks = np.array([88, 90, 30, 45, 75])

mark_add = marks>45

print(mark_add)

[ True  True False False  True]


In [8]:
print(marks[0])

88


In [8]:
,marks[:3] #slicing 

TypeError: 'numpy.ndarray' object is not callable

In [12]:
b1 = np.array([56,78,89])
b2=np.array([65,76,98])

comp = np.concatenate((b1,b2))
comp


array([56, 78, 89, 65, 76, 98])

In [13]:
print(np.split(comp,2))

for arr in np.split(comp,3):
    print(arr)

[array([56, 78, 89]), array([65, 76, 98])]
[56 78]
[89 65]
[76 98]


In [7]:
mark=np.array([[85,78,90],
      [92,85,98],
      [76,82,80]])

print(np.where(mark>=78))
print(mark)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64), array([0, 1, 2, 0, 1, 2, 1, 2], dtype=int64))
[[85 78 90]
 [92 85 98]
 [76 82 80]]


In [6]:
np.array(['ram',45,True])


array(['ram', '45', 'True'], dtype='<U11')